language: php

php:
  - 7.4
  - nightly

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly

install:
  - composer require satooshi/php-coveralls:@stable --dev --no-update
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - mkdir -p build/logs
  - vendor/bin/phpstan analyse
  - vendor/bin/phpcs
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=/tmp/coverage.xml -v
